### ISSUE TITLE
Get landing pages for a specific campaign ?

### ISSUE THREAD

**Issue by J3remyD** [googleads/googleads-dfa-reporting-samples#15]
Hello,
with the new API version 3.0, I can't get landing pages for a specific campaign anymore, as far as I know the API.
Either I do this => `reporting.advertiserLandingPages().list(profileId).execute().getLandingPages()` which returns me everything landing pages I have but I can't filtered them with a campaign Id because the LP object doesn't hold a campaign id attribute ..... 
Or I can do the following `reporting.campaigns().get(profileId, DfaCampaignId).execute()` which returns a campaign object but without being able to access attached/related landing pages again because there's no related attribute to do so anymore.

Can you help me out with this ?

**Comment by jimper** [comment]
Landing page management has moved from the [campaign level to the advertiser level](https://developers.google.com/doubleclick-advertisers/rel_notes#known-issues) in DCM. Campaigns now just hold a reference to a single default advertiser landing page. You can either get the campaign and look up the landing page it references by ID, or [list all landing pages for the campaign's advertiser](https://github.com/googleads/googleads-dfa-reporting-samples/blob/master/python/v3_0/get_advertiser_landing_pages.py#L50).

Regards,
-- Jonathon Imperiosi, DCM API Team

**Comment by J3remyD** [comment]
Hi Jonathon,

thanks for you answer, I get that the LPs were moved, no problems. But how do you look the landing pages referenced by campaign Id, I'm no able to do that anymore. In a campaign object I only have a default landing page id. Also listing all LPs of a campaign's advertiser is super great, but it's now what I want, I have more than one campaign attach to the same advertiser, so if I list them I will get thousand of unrelated LPs that's precisely my point :-(.

Thanks

**Comment by jimper** [comment]
Unfortunately the old workflow of looking up LPs by campaign ID isn't supported, since campaigns don't have a direct relationship to LPs anymore. The defaultLandingPage in the campaign is the only association that exists (there's no longer a concept of campaigns being associated with multiple LPs).

If you have a list of campaign IDs, you could look up all the associated default LPs in a few steps:

1. Call campaigns.list, filter by campaign IDs
2. Collect defaultLandingPageIds from the campaigns
3. Call advertiserLandingPages.list, filter by landing page IDs
