### ISSUE TITLE
run_report.py not working version 3.3

### ISSUE THREAD

**Issue by Ankan1991** [googleads/googleads-dfa-reporting-samples#22]
Hi,

For version 3.3 for python "run report"
Py version - 3.6.7

I was succesfully able to use the python version of the code , however today I encountered errors:

Adding traceback.

`Traceback (most recent call last):
  File "run_report.py", line 97, in <module>
    main(sys.argv)
  File "run_report.py", line 58, in main
    reportId=report_id).execute()
  File "C:\Users\MukheAnk\AppData\Local\Continuum\anaconda3\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\MukheAnk\AppData\Local\Continuum\anaconda3\lib\site-packages\googleapiclient\http.py", line 851, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 500 when requesting https://www.googleapis.com/dfareporting/v3.3/userprofiles/5071036/reports/524471992/run?alt=json returned "">`

Adding another trace if it helps:

`callback(resp)
    850     if resp.status >= 300:
--> 851       raise HttpError(resp, content, uri=self.uri)
    852     return self.postproc(resp, content)
HttpError: <HttpError 500 when requesting https://www.googleapis.com/dfareporting/v3.3/userprofiles/5071036/reports/524471992/run?alt=json returned "">`

**Comment by jimper** [comment]
Hi there,

This seems to be an issue with the report you're trying to run, rather than with the sample itself. Please open a thread on our [API support forum](https://groups.google.com/forum/#!forum/google-doubleclick-for-advertisers-api) with details of how you created this report and whether or not you're able to reproduce the issue with other reports. You should also familiarize yourself with [how to enable HTTP logging](https://developers.google.com/api-client-library/python/guide/logging#http-traffic) for the Python client library in case our support agents ask for more detailed logs.

Regards,
\- Jonathon Imperiosi, DCM API Team
